### ISSUE TITLE
Consider moving away from storyblok-migrate to use official storyblok-cli migrate commands

### ISSUE THREAD

**Issue by heresandyboy** [apjames93/mui-storyblok#120]
`storyblok-migrate` does not work with any projects that have dependencies that have upgraded to corejs 3.
This means that mui-storyblock can't run the migration if used in a new project.

This is due to a bunch of breaking changes in corejs3 (I've actually been chasing this same issue around github and submitting pull requests to fix it for anything I'm trying to use).

Errors like this occur.
```
Cannot find module core-js/modules/es6.regexp.split
```

I have just submitted a pull request to `storyblock-migrate` in order to update their dependencies. Latest version of `storyblok-js-client` has support for corejs3 [https://github.com/maoberlehner/storyblok-migrate/pull/10](https://github.com/maoberlehner/storyblok-migrate/pull/10). I can confirm my changes have fixed the issues by yarn linking my branch to your package.

I was going to submit a pull request to update your dependencies once `storyblok-migrate` is up to date but I have just noticed a line in the storyblok docs [https://www.storyblok.com/tp/content-and-component-migrations-with-storyblok-migrate](https://www.storyblok.com/tp/content-and-component-migrations-with-storyblok-migrate)

> Update: We recommend to use the new content migration functionality of [Storyblok’s CLI](https://github.com/storyblok/storyblok#content-migrations).

It looks like storyblok have since rolled their own solution for migrations using their CLI. Do you think it's worth thinking about moving over to that instead of using a package like [https://github.com/maoberlehner/storyblok-migrate](https://github.com/maoberlehner/storyblok-migrate) which looks to have been made by someone unconnected to storyblok and hasn't seen a lot of activity in the last year.

**Comment by heresandyboy** [comment]
Pull request [maoberlehner/storyblok-migrate#10](maoberlehner/storyblok-migrate#10) was merged and pushed to npm.
v0.3.4 includes the updated dependencies to support corejs 3. 

I'll leave it up to you @apjames93 to decide if you want to upgrade to the updated storyblok-migrate or have a look into using the new official CLI for migrations instead.

I'd say that anyone including these corejs upstream changes should really be issuing a major update and make it clear in the release notes that it is a breaking change.

Each package that upgrades to corejs3 based dependencies will break backwards compatibility with other corejs v2x packages. I just wish corejs had thought about the impact this is having and just forwarded the old APIs to their new renamed ones and just issued npm warnings to tell people to update their code for a version or two. You won't believe the amount of github issues I've read from loads of different projects due to this.

**Comment by apjames93** [comment]
@heresandyboy I think that is a great idea! I have wanted to get away  from storyblock-migrate from the get go because it has not been maintained and has a few bugs. It was just easy to get something going quickly when the project was started and i didnt know that storyblok had a package to do the same thing. I will put this on the list of todos and for now we can update the storyblok-migrate to version 0.3.4 for a quick fix.

**Comment by apjames93** [comment]
@heresandyboy hey if you want to take a look we went though and swapped out for the storyblok cli in version 1.1.03 it looks like it is all working. Thanks for opening the issue and the help so far!
